"use client";

import { useState } from "react";
import { CheckCircle, AlertCircle, RefreshCw } from "lucide-react";

export default function RequirementsTab({ projectId }) {
  // Mock data for UI development. In reality, this is generated by the AI
  // analyzing the interview transcript and saved in Firestore.
  const [requirements, setRequirements] = useState({
    revision: 1,
    hash: "abc123def456",
    isConfirmed: false,
    content: {
      facts: ["User wants an e-commerce store.", "Target audience is mobile users."],
      assumptions: ["Using Stripe for payments.", "Shipping only domestic."],
      exclusions: ["No physical storefront integration.", "No multi-currency support yet."],
      openQuestions: [],
      conflicts: []
    }
  });

  const [isConfirming, setIsConfirming] = useState(false);

  const handleConfirm = async () => {
    setIsConfirming(true);
    // Simulate API call
    setTimeout(() => {
      setRequirements(prev => ({ ...prev, isConfirmed: true }));
      setIsConfirming(false);
    }, 1000);
  };

  const handleRequestChanges = () => {
    // Navigates back to interview or triggers a new AI analysis
    alert("This would return you to the Interview tab to discuss changes.");
  };

  const isReadyForConfirmation = requirements.content.openQuestions.length === 0 && requirements.content.conflicts.length === 0;

  return (
    <div className="flex flex-col h-full bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div className="p-6 border-b border-gray-200 bg-gray-50 flex justify-between items-start">
        <div>
          <h3 className="text-lg font-bold text-gray-900">Project Requirements</h3>
          <p className="text-sm text-gray-500 mt-1">
            Revision {requirements.revision} • <span className="font-mono text-xs bg-gray-200 px-1 rounded">{requirements.hash.substring(0, 8)}</span>
          </p>
        </div>

        {requirements.isConfirmed ? (
          <div className="flex items-center gap-2 text-green-700 bg-green-50 border border-green-200 px-4 py-2 rounded-lg font-medium text-sm">
            <CheckCircle size={18} />
            Scope Confirmed
          </div>
        ) : (
          <div className="flex items-center gap-2 text-amber-700 bg-amber-50 border border-amber-200 px-4 py-2 rounded-lg font-medium text-sm">
            <AlertCircle size={18} />
            Pending Confirmation
          </div>
        )}
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-8">

        {requirements.content.conflicts.length > 0 && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4">
            <h4 className="font-semibold text-red-800 mb-2 flex items-center gap-2">
              <AlertCircle size={18} /> Blocking Conflicts
            </h4>
            <ul className="list-disc list-inside text-sm text-red-700 space-y-1">
              {requirements.content.conflicts.map((c, i) => <li key={i}>{c}</li>)}
            </ul>
          </div>
        )}

        {requirements.content.openQuestions.length > 0 && (
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
            <h4 className="font-semibold text-amber-800 mb-2 flex items-center gap-2">
              <AlertCircle size={18} /> Unresolved Questions
            </h4>
            <ul className="list-disc list-inside text-sm text-amber-700 space-y-1">
              {requirements.content.openQuestions.map((q, i) => <li key={i}>{q}</li>)}
            </ul>
          </div>
        )}

        <section>
          <h4 className="font-bold text-gray-800 mb-3 border-b pb-2">Confirmed Facts</h4>
          <ul className="space-y-2">
            {requirements.content.facts.map((fact, i) => (
              <li key={i} className="flex gap-3 text-gray-700 text-sm">
                <span className="text-blue-500 mt-0.5">•</span> {fact}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h4 className="font-bold text-gray-800 mb-3 border-b pb-2">Architect Assumptions</h4>
          <ul className="space-y-2">
            {requirements.content.assumptions.map((assumption, i) => (
              <li key={i} className="flex gap-3 text-gray-700 text-sm">
                <span className="text-purple-500 mt-0.5">✦</span> {assumption}
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h4 className="font-bold text-gray-800 mb-3 border-b pb-2">Explicit Exclusions</h4>
          <ul className="space-y-2">
            {requirements.content.exclusions.map((exclusion, i) => (
              <li key={i} className="flex gap-3 text-gray-700 text-sm">
                <span className="text-red-500 mt-0.5">×</span> {exclusion}
              </li>
            ))}
          </ul>
        </section>
      </div>

      <div className="p-4 border-t border-gray-200 bg-gray-50 flex justify-end gap-3">
        {requirements.isConfirmed ? (
           <button
             onClick={handleRequestChanges}
             className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-100 transition-colors"
           >
             Modify Scope (Invalidates Confirmation)
           </button>
        ) : (
          <>
            <button
              onClick={handleRequestChanges}
              className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-100 transition-colors"
            >
              Request Changes
            </button>
            <button
              onClick={handleConfirm}
              disabled={!isReadyForConfirmation || isConfirming}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {isConfirming ? <RefreshCw size={16} className="animate-spin" /> : <CheckCircle size={16} />}
              Confirm Requirements
            </button>
          </>
        )}
      </div>
    </div>
  );
}
